### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by neuromancer** [codenamecpp/carnage3d#1]
Hi, 

Any plans for Linux support of this neat reimplementation? 

Thanks!

**Comment by codenamecpp** [comment]
Hi,
I'm not familiar with Linux OS, but I think that it is quite possible. Although I will need some expert assistance :)

**Comment by codenamecpp** [comment]
Just added linux support, tested on Ubuntu - it works!

**Comment by neuromancer** [comment]
Great job, I can provide some testing in Linux if you need!
