### ISSUE TITLE
[Graphics] Implement sprite remaps

### ISSUE THREAD

**Issue by codenamecpp** [codenamecpp/carnage3d#11]
This includes:
- [x] - Block remaps
- [x] - Cars remaps
- [x] - Pedestrian remaps

**Comment by codenamecpp** [comment]
Done

**Comment by MiroslavR** [comment]
Out of curiosity, what are the block remaps? Could you give an example?

**Comment by codenamecpp** [comment]
As far I know, block remaps are used just for shading.
For example, remaps enabled: https://gyazo.com/95a2b714aa52b92df59c65f75dee8fd2
And disabled: https://gyazo.com/6554a5060d60ea631344b6ba525e9e8c

**Comment by MiroslavR** [comment]
Ah, thanks!
