### ISSUE TITLE
Game freezes when interacting with debug window

### ISSUE THREAD

**Issue by MiroslavR** [codenamecpp/carnage3d#16]
When I expand the "Ped" section in the debug window or open the console, the player character disappears and _sometimes_ the game freezes for about 30 seconds. My whole system is barely responsive in that time.

**Comment by MiroslavR** [comment]
It seems that during this "freeze", the game does render and update but the frames are taking abnormally long and are seemingly very CPU intensive...

The effect is much worse when turning off VSync.

**Comment by neuromancer** [comment]
I had the same issue, but I didn't report it because I thought it was a some hardware-related problem (`dmesg` was reporting some Nvidia error commonly associated with that).

**Comment by codenamecpp** [comment]
Hm, very interesting.
I think this somehow related to imgui rendering. First thing come in mind is to make work imgui renderer harded - I have just added one option to cfg "show_imgui_demo_window" - this will enable imgui demo window with bunch of controls, texts etc. 
Please test it and try to find steps which reproduces freeze.

**Comment by MiroslavR** [comment]
Unfortunately, after enabling the option, the game freezes on launch and doesn't unfreeze, so I can't really play with the controls. I can see the windows and they update infrequently. The metrics window reports normal average framerate.

**Comment by MiroslavR** [comment]
I also get Nvidia messages in dmesg, where the pid is the process ID of carnage3d:
```
[  568.853043] NVRM: Xid (PCI:0000:01:00): 8, pid=2662, Channel 00000018
```

Also Xorg seems to eat 100% CPU during the freeze. I've updated my Nvidia driver, but to no avail.

**Comment by MiroslavR** [comment]
I've tried compiling https://github.com/ocornut/imgui/tree/master/examples/example_glfw_opengl3. It shows the same demo window but doesn't freeze.

**Comment by MiroslavR** [comment]
I've done a `git bisect`. The first bad commit is 415b6103a9eab3164f8511b658e6b112ac6daa11 - before that there were no freezes.

**Comment by codenamecpp** [comment]
Thanks, **MiroslavR** :)
Sure that will help!

**Comment by codenamecpp** [comment]
I made a few changes in the code, could you please test it again?

**Comment by MiroslavR** [comment]
That fixed it. :+1:

**Comment by codenamecpp** [comment]
Great! 
Thanks for assist.
