### ISSUE TITLE
Continuous Integration Testing

### ISSUE THREAD

**Issue by neuromancer** [codenamecpp/carnage3d#2]
It's never too early for CI testing!

I recommend to setup CI using websites like [TravisCI](https://travis-ci.com/) since they allow to specify Window/Linux systems and they are integrated with Github. Let me know if you need help with this.

**Comment by codenamecpp** [comment]
Oh yes, I'm working on it right now, trying to get things work.
Need a bit more time to figure out details.

**Comment by codenamecpp** [comment]
Hm, something strange is going on.
Cannot build project on Travis because of error
> error: use of undeclared identifier 'isfinite' in Box2D/Common/b2Math.

The Box2d itself is building OK, but when compile carnage3d with box2d headers included then that error happened.

Next error even more strange:
> no member named 'glfwSetWindowMonitor' in the global namespace

Wtf? On my Linux Lite all complies perfectly...

**Comment by neuromancer** [comment]
I can take a look later today.

**Comment by codenamecpp** [comment]
It would be great !

Here, one of logs: https://gist.github.com/codenamecpp/54fb90526ccdd48107a9c416e3639e80

**Comment by codenamecpp** [comment]
Awesome, it's works, build is success now. Thank you for help, **neuromancer**!
