### ISSUE TITLE
[Gameplay] Add split screen feature

### ISSUE THREAD

**Issue by codenamecpp** [codenamecpp/carnage3d#21]
I would like to add cooperative / deathmatch in hot-seat mode so split screen is a must. Support up to 4 players.

Tasks:
- [x] Implement per-player viewport with own camera and camera controller
- [x] Split screen layouts
- [ ] Efficient off-screen objects culling mechanism
- [x] Add command line parameters to start game in split screen mode
- [x] Rewrite map blocks cache&render mechanism

**Comment by neuromancer** [comment]
[GTA2: Hacker's Remix mod](https://github.com/Bytewerk/gta2-hackers-remix) contains some interesting ideas on how to arrange the layout for more than two players.

**Comment by codenamecpp** [comment]
Implemented in [5d8c3a5] and kinda works : https://gyazo.com/d7b5849a3535a628c02bcc25d72863e4
Max 4 players in split screen mode is supported, to set num players add param **-numplayers N** in command line, where N is number from 1 to 4.
Still need to add efficient off-screen objects culling and refactore some classes but it is good for now.

**Comment by MiroslavR** [comment]
Doesn't work with 2 players - only the first player's view is visible.

**Comment by codenamecpp** [comment]
Oops, fixed :)
