### ISSUE TITLE
[Gameplay] Add support for mouse aiming

### ISSUE THREAD

**Issue by neuromancer** [codenamecpp/carnage3d#22]
It will be nice to support the use of the mouse for aiming as the [gta2-mouse mod](https://github.com/h0x91b/gta2-mouse).

**Comment by codenamecpp** [comment]
But how to combine it with #21 ? Only player 1 can aim with mouse and it's not fair :)

**Comment by codenamecpp** [comment]
Added console varriable "mouse_aiming", it will activate mouse aiming for player 1.
