### ISSUE TITLE
[Repo] Include GLFW as git submodule

### ISSUE THREAD

**Issue by codenamecpp** [codenamecpp/carnage3d#24]
GLFW 3.3 is not available via apt-get on linux bionic.

**Comment by codenamecpp** [comment]
I have add glfw git submodule to repo but I no idea how to integrate it to premake :)
So I'll be appreciated for help.

**Comment by neuromancer** [comment]
An example is here: https://github.com/premake/premake-core/wiki/Tutorial-Premake-example-with-GLFW-and-OpenGL

I can take a look later to this.

**Comment by codenamecpp** [comment]
it would be great, **neuromancer**!

**Comment by neuromancer** [comment]
After some research, my conclusion is that GLFW cannot be directly integrated using premake (Well, it is technically possible, but it will be hard to do and maintain). The options are:
* Use premake to include only the headers and provide a precompiled version of the library (this is already available from the GLFW website for Windows and MacOS). This should be easy, but it could not work for all the Linux distros (some distros like ArchLinux already have GLFW 3.3 available, so it should be tested primarily in Ubuntu/Fedora).
* Use premake to run the corresponding cmake command to compile GLFW 3.3. This is slightly more difficult and require the user to install some extra packages (e.g. cmake), but it should work for all the Linux versions.


So, what do you think?

**Comment by codenamecpp** [comment]
Thanks for research!
I have noticed that box2d which compiling with project has already glfw included (as part or testbed). So I think we could just do the same thing?

**Comment by neuromancer** [comment]
It seems glfw 3.3 is statically linked in box2d. I'm looking how to integrate this directly into the main build right now..

**Comment by codenamecpp** [comment]
Done in [c5af138]
GLFW 3.3 will not statically compile on LINUX
