### ISSUE TITLE
[Gameplay] Weapons

### ISSUE THREAD

**Issue by codenamecpp** [codenamecpp/carnage3d#26]
This incudes:
- [x] Implement all types of weapons
- [x] Projectiles
- [x] Explosions
- [x] Damage for cars and pedestrians

**Comment by codenamecpp** [comment]
Done, more or less. although it not final yet.

**Comment by neuromancer** [comment]
Wow, cool, this need some new screenshots / video to celebrate!

**Comment by codenamecpp** [comment]
Why not :)
https://youtu.be/KnqaO0YZzZY
