### ISSUE TITLE
Support the GTA demos

### ISSUE THREAD

**Issue by neuromancer** [codenamecpp/carnage3d#3]
Unfortunately, [Rockstar no longer offers](https://www.rockstargames.com/classics/) the original GTA for free. However, [some demos are still available](https://www.rockstargames.com/gta/extras/demos.html). I tried the demos, and Carnage3D seems to work (at least partially) with them (but you need to un-comment the proper .CMP to load: for instance, NYC instead of MIAMI).

In summary, supporting the demos will allow people to quickly test this neat reimplementation :smile:

**Comment by codenamecpp** [comment]
Great idea!
While level selection feature is missing for now, I think it might be useful to add command line parameter to choose map.

**Comment by codenamecpp** [comment]
Done:
- added command line param to choose level: **-mapname SANB.CMP**
- if it not specified, defaults to NYC.CMP

Tested on demo 04 - works fine.
