### ISSUE TITLE
Sluggish input while standing and punching

### ISSUE THREAD

**Issue by MiroslavR** [codenamecpp/carnage3d#32]
Try switching the turning direction multiple times while standing and punching. The input is delayed. No problem while running, only standing.

I'm on commit aeea1b5c0f3507deeed90e558971f8d1f6c81a90.

**Comment by codenamecpp** [comment]
Oh yes, it's should be better now.

**Comment by MiroslavR** [comment]
Yes, turning is better now. But moving forward/backward suffers from the same issue.

**Comment by codenamecpp** [comment]
Now I'm in confuse.
Do you mean that after the punch while standing still, ped cannot move forward/backward until animation finished? If so, then it is'nt issue - it is close to what was in the original game.

**Comment by MiroslavR** [comment]
Yes. It just feels awkward. I don't remember the original game behaving like that, but it's been a long time since I played it. Feel free to close this issue if the behavior matches.

**Comment by codenamecpp** [comment]
I think we can step a little away from the canon in this case :)
Please, test it again.

**Comment by MiroslavR** [comment]
Much better, thanks!

Anyway, I've just managed to run the original. What you said is true if you press and release CTRL. But if you hold CTRL, you can move just fine. Though there is a glitch (talking about the original): if you stop moving while holding CTRL, your character will visually stop punching but only visually - he is actually still punching in reality.

**Comment by codenamecpp** [comment]
It's funny glitch :) I think there is no reason to emulate it in remake but knowing about it is rather useful.

Please reopen thin issue if there will be some ideas on how to improve this mechanics.

**Comment by MiroslavR** [comment]
Yeah, I agree there is no reason to replicate it. I think the current Carnage3D behavior is fine.
