### ISSUE TITLE
Zoom in should have reasonable limit

### ISSUE THREAD

**Issue by neuromancer** [codenamecpp/carnage3d#39]
Otherwise, it goes through the floor.

**Comment by codenamecpp** [comment]
Current camera implementation is temporary as well as many other things in game :)
Although of course I can fix it.

**Comment by codenamecpp** [comment]
Done!

**Comment by neuromancer** [comment]
It works!. The only detail: if you switch to free look, you can still zoom through the floor.

**Comment by codenamecpp** [comment]
Ah, i'm forgot about that camera mode :)
Fixed.
