### ISSUE TITLE
Visual studio build error

### ISSUE THREAD

**Issue by aash29** [codenamecpp/carnage3d#40]
Hi, I'm getting the following error when trying to compile with Visual Studio 2015:

Error	MSB8020	The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	

If I do 'retarget solution', i get 

We were unable to automatically populate your Visual Studio Team Services accounts.
    
The following error was encountered: VS30063: You are not authorized to access https://app.vssps.visualstudio.com.Retargeting End: 1 completed, 0 failed, 0 skipped

**Comment by codenamecpp** [comment]
I'm using v140 platform toolset, try to open menu "Project"->Properties->Configuration Properites->General - and choose platform toolset v140 for all projects in solution.

**Comment by aash29** [comment]
it worked, i had some more path issues but was able to build it at last

**Comment by aash29** [comment]
looks good! do you plan on doing anything more with this remake?

**Comment by codenamecpp** [comment]
Thanks )

Well, i'd like to make it playable, support original missions progressing, weapons, DLCs maybe.

But currently it is hard to say when I'll back to this project as I have more important things to do right now.
