### ISSUE TITLE
Game freeze on MIAMI.CMP

### ISSUE THREAD

**Issue by MiroslavR** [codenamecpp/carnage3d#49]
After 9c0361c62c61af28a888e941fc8077e2e8f1b755, the game stops responding when loading the map MIAMI.CMP. I am not familiar with the code but I can see `SpriteAnimation::UpdateFrame` looping forever because `mAnimDesc.mFrameRate` evaluates to infinity.

**Comment by codenamecpp** [comment]
Thanks! Fixed now.
