### ISSUE TITLE
Graphical artifacts

### ISSUE THREAD

**Issue by MiroslavR** [codenamecpp/carnage3d#5]
When I'm moving around, walls tend to flicker like hell. Additionally, after changing elevation or zooming in/out, some of the horizontal tiles spaz out for a second, frequently switching between textures. I'm on Linux (Debian).

Screenshot:
![bug](https://user-images.githubusercontent.com/7346770/66273920-2458d880-e879-11e9-9a72-e23ba8a6f517.png)

Output:
```
$ ./bin/carnage3d-debug -mapname SANB.CMP
System initialize
Working directory: '/data/git/carnage3d/bin'
Screen resolution: 1600x900, Vsync: disabled
gta_gamedata_location: '/data/Games/GTA/GTAINSTALLER/extracted/Program_Executable_Files/GTADATA'
GLFW Information: 3.3.0 X11 GLX EGL OSMesa clock_gettime evdev shared
Initialize OpenGL 3.2 (Core profile)
Screen resolution (1600x900)
OpenGL Vendor: NVIDIA Corporation
OpenGL Renderer: GeForce GTX 660/PCIe/SSE2
OpenGL Version: 3.2.0 NVIDIA 418.74
GLSL Version: 1.50 NVIDIA via Cg compiler
Render program loaded shaders/texture_color.glsl
Render program loaded shaders/gui.glsl
Render program loaded shaders/city_mesh.glsl
Render program loaded shaders/sprites.glsl
Render program loaded shaders/debug.glsl
System shutdown
```

**Comment by codenamecpp** [comment]
Hm, looks like some bug in shaders code.
Could you please run some tests to help me understand what is going on?

First, get latest source from repository and compile it. I've added one extra log string which is tell how much texture array leyers supported in your gpu. I hope its value is at least 512 :)

Second, do some experiments with shaders code. Run the game and open city_mesh.glsl file in text editor (keep game running). You will need use 'shaders hot reloading' key - F3.
Then find string in shader
`pixelColor = texture(tex_0, vec3(Texcoord.x, Texcoord.y, block_texture_index));`
and change `block_texture_index` to 1.0, save file and press F3 key in game. You should now see the picture : https://gyazo.com/ef83abbe19c8c9290d6f48fd5b2cf124
Note that the picture must be stable (if it is not - then problem might be somewhere else).

Play with this value within range 1.0 - 255.0.

**Comment by neuromancer** [comment]
I can reproduce all these issues using [this demo](https://www.rockstargames.com/gta/demos/gtaects.zip) in the latest revision (dd22828a979feeb566a59b03c5a138730c70e80d).

**Comment by codenamecpp** [comment]
Okay, demo is fine.

**Comment by neuromancer** [comment]
> Then find string in shader
pixelColor = texture(tex_0, vec3(Texcoord.x, Texcoord.y, block_texture_index));
and change block_texture_index to 1.0, save file and press F3 key in game. You should now see the picture : https://gyazo.com/ef83abbe19c8c9290d6f48fd5b2cf124
Note that the picture must be stable (if it is not - then problem might be somewhere else).

After following your instructions, the picture is similar and the image is stable. However, I can't really deduce anything from changing `block_texture_index` to a number from 1.0 to 255.0. It seems to works correctly every time. I tried using `int(block_texture_index) % X` (where X is a number between 1 and 255) and gradually the issue is exposed, but I don't understand what going on enough to determinate exactly how this issue is triggered.

**Comment by codenamecpp** [comment]
Please tell the number of texture array layers - message "Graphics Device supports up to the %d array texture layers" in console window

**Comment by neuromancer** [comment]
Oh, sorry. It's this:

> Graphics Device supports up to the 2048 array texture layers

**Comment by codenamecpp** [comment]
Thank you. I will try to figure what exactly is causing this problem.

**Comment by MiroslavR** [comment]
Pretty neat that you can change shaders on the fly! Anyway, I can confirm neuromancer's findings - using a constant for `block_texture_index` makes everything stable. I have 2048 array texture layers as well.

**Comment by codenamecpp** [comment]
Okay, here one more thing to try: replace 
`pixelColor = texture(tex_0, vec3(Texcoord.x, Texcoord.y, block_texture_index));`

with this:

`pixelColor = texture(tex_0, vec3(Texcoord.x, Texcoord.y, Texcoord.z));`

Did it help?

**Comment by MiroslavR** [comment]
Yes, that completely fixes the issue for me.

**Comment by codenamecpp** [comment]
Okay, great, the problem is in blocks animation texture, so I'll temporarily disable it.

**Comment by MiroslavR** [comment]
Found another artifact:
![bug2](https://user-images.githubusercontent.com/7346770/66321904-91c04400-e921-11e9-80be-375d28f813f3.png)
![bug3](https://user-images.githubusercontent.com/7346770/66323133-9e459c00-e923-11e9-88ef-87672b36d35e.png)

The red roof has transparency issues when zooming in/out or in free look camera. The second building (as well as many other buildings) always show the issue. Seems like these transparent spots should be black?

Disabling alpha test fixes the issue (but obviously the things that should be transparent are now not).

**Comment by codenamecpp** [comment]
Okay, so I've upload few changed and it's should fix it. Please try it.

**Comment by MiroslavR** [comment]
All is good now. Nice job!

**Comment by codenamecpp** [comment]
Hooray !
Thanks for reporting issue and patience :)
