### ISSUE TITLE
Allow to use system GLFW

### ISSUE THREAD

**Issue by kattjevfel** [codenamecpp/carnage3d#55]
Just like the ticket about Box2D, allowing users to use their system-wide GLFW would mean less to compile and less space wasted.

**Comment by codenamecpp** [comment]
It was added on purpose - system GLFW3 on bionic ubuntu is lacking gamepads support so I decided to include latest version of GLFW3 to project.

**Comment by kattjevfel** [comment]
Sure, but what I'm asking for is an option to not use that, which someone not using bionic ubuntu can use.

**Comment by marmichalski** [comment]
I believe this can be closed, @kattjevfel? The newly introduced [cmake build](https://github.com/codenamecpp/carnage3d/pull/68) currently only looks for system GLFW.

**Comment by kattjevfel** [comment]
Nice!
