### ISSUE TITLE
Build error on Linux

### ISSUE THREAD

**Issue by MiroslavR** [codenamecpp/carnage3d#57]
```
../src/WeatherManager.cpp:5:10: fatal error: 'Cvars.h' file not found
#include "Cvars.h"
         ^~~~~~~~~
```
Changing it to `#include "cvars.h"` solves the issue.

BTW, can I ask what this weather stuff is all about? Is it to support the Snowball City mod? I don't recall the original game having weather.

**Comment by codenamecpp** [comment]
Fixed.

I was just messing around with particles and thought it was good idea to add some simple weather effects like snow or rain. It is optional and disabled by default.

**Comment by MiroslavR** [comment]
Ah, okay. The snowfall effect in Snowball City is unrelated then. I've just checked and Carnage3D does support it (because it's probably just animated sprites in the highest layer of the map). Anyway, thanks for the fix.
