### ISSUE TITLE
Incorrect rate of fire and ammo consumption

### ISSUE THREAD

**Issue by MiroslavR** [codenamecpp/carnage3d#58]
Here's a table illustrating the timing differences of weapons being emptied from full (99) ammo:

| Weapon | Original game | Carnage3D |
|--|--|--|
| Pistol | ~42s | ~50s |
| Machine gun | ~21s | ~13s |
| Flamethrower | ~21s | ~7.5s |
| Rocket launcher | ~84s | ~98s |

MG and flamethrower empty way too fast in Carnage3D. They also seem to produce fewer projectiles - Carnage3D considers 1 ammo = 1 projectile, whereas the original game has several projectiles (5?) for 1 ammo.

**Comment by codenamecpp** [comment]
Wow, that's an exhaustive comparison, thanks! :)

**Comment by codenamecpp** [comment]
It should be pretty close now, although not 100% accurate. These weapon timings can be configured via gamedata/entities/weapons.json so it is possible to play with.
