### ISSUE TITLE
Boat wrecks look incorrectly

### ISSUE THREAD

**Issue by MiroslavR** [codenamecpp/carnage3d#60]
Carnage3D:
![image](https://user-images.githubusercontent.com/7346770/103024972-24fa8f00-4551-11eb-9bdd-22bab5008517.png)
GTA 1: 
![image](https://user-images.githubusercontent.com/7346770/103024994-32b01480-4551-11eb-9435-a2184da726aa.png)

The screenshot is modded but it is possible to see the boat wreck in one official mission where you have to blow up a boat. Of course that makes it a very minor issue. :smile:

**Comment by codenamecpp** [comment]
Oops, haven't seen this sprite before for some reason. luckily this is very easy to fix :)
