### ISSUE TITLE
Weapons sound differently

### ISSUE THREAD

**Issue by MiroslavR** [codenamecpp/carnage3d#62]
The original game:
1. Stops the existing weapon sound when you fire, i.e. it doesn't allow weapon sounds to overlap. 
2. Seems to randomize the pitch.

**Comment by codenamecpp** [comment]
Hi!
1. OK, it might be not hard to fix
2. It is applies not only to weapons but also for many other sound effects in game so fixing is beyond the scope of this task

**Comment by codenamecpp** [comment]
Did a bit refactore to sound manager last night, so now both of these issues hopefully resolved
