### ISSUE TITLE
Console opening/closing keys are inconsistent

### ISSUE THREAD

**Issue by MiroslavR** [codenamecpp/carnage3d#64]
The console can be opened with the key under ESC, independent of keyboard layout. But the closing key is not necessarily the same - it does depend on keyboard layout. My keyboard layout (Slovak) requires me to do a pretty wild combination of keystrokes to produce a backtick and close the console. I think both situations should use scancodes.

**Comment by codenamecpp** [comment]
I came up with not particularly elegant solution but it good for now
