### ISSUE TITLE
Gamedata is required to be in all uppercase

### ISSUE THREAD

**Issue by kattjevfel** [codenamecpp/carnage3d#74]
At least on the copy I have, both on the CD and once installed, all files are in lowercase, causing carnage3d to fail to find the gamedata, I worked around this by renaming all files to be uppercase, but I feel that shouldn't be needed.

```
Current gta gamedata location is: '/home/katt/.wine/drive_c/GTA/gtadata/'
No gta maps found within search places
Set valid gta gamedata location via sys config param 'g_gtadata'
Cannot open texts file 'ENGLISH.FXT'
Fail to load game texts for current language
Map name is not specified
Fail to start game
Cannot initialize game
System shutdown
```

**Comment by codenamecpp** [comment]
Hi, @kattjevfel !
Both retail version which I'm own and "Grand Theft Auto: Max Pack" comes with files almost all named in upper case. Same for demo versions of game. I'm wondering what version of the game you have?

**Comment by kattjevfel** [comment]
Well now I feel stupid, after looking into it a bit further, this seems to be a bug in CDEmu. For whatever reason when mounting my image it turned all files into lowercase, looking inside the iso with an archive tool they are indeed all uppercase... pebkac at it again!
