### ISSUE TITLE
Feature request: Release early, release often

### ISSUE THREAD

**Issue by neuromancer** [codenamecpp/carnage3d#8]
I'm following other game re-implementation like [OpenNitemare3D](https://github.com/BBQGiraffe/OpenNitemare3D). The developer produces [releases often](https://github.com/BBQGiraffe/OpenNitemare3D/releases) every time a new feature is implemented and needs testing. I wonder if the same approach could be followed during the development of Carnage3D.

**Comment by codenamecpp** [comment]
I believe that the project isn't quite nearly at point where features testing is required. A lot of thing is temporary or barely works (physics and collisions for example) and will be improved gradually as the  development goes on.
But I agree that 'milestones' is needed to make progress more noticeable.

**Comment by codenamecpp** [comment]
Added first milestone - Tier 0
